import os

kode_baru = """
# === KOMPILATOR OUROLANG FINAL (BINARY BOOTSTRAP V4.0) ===
BAWAKAN "kompilator/modul_lexer.ouro"
BAWAKAN "pustaka/bin_writer.ouro"
BAWAKAN "pustaka/ouro_core.ouro"

FUNGSI_PARAM TULIS_BYTE FD DATA
    TULIS_KARAKTER FD DATA
BATAS_FUNGSI

# --- FUNGSI BARU: PARSER ANGKA AMAN ---
FUNGSI_KEMBALI STRING_KE_ANGKA
    SIMPAN HASIL 0
    SIMPAN IDX 0
    SIMPAN KAR 0
    SIMPAN DIGIT 0
    SELAMA_KURANG IDX PANJANG_TOKEN
        ARRAY_AMBIL KAR BUFFER_TOKEN IDX
        SIMPAN DIGIT KAR
        KURANG DIGIT 48
        KALI HASIL 10
        TAMBAH HASIL DIGIT
        NAIK IDX
    BATAS_SELAMA
    KEMBALIKAN HASIL
BATAS_FUNGSI

# --- FUNGSI BARU: PENULIS 4-BYTE LITTLE-ENDIAN ---
FUNGSI_PARAM TULIS_ANGKA_4BYTE FD_OUT ANGKA
    SIMPAN SISA ANGKA
    PANGGIL_PARAM TULIS_BYTE FD_OUT SISA
    BAGI SISA 256
    PANGGIL_PARAM TULIS_BYTE FD_OUT SISA
    BAGI SISA 256
    PANGGIL_PARAM TULIS_BYTE FD_OUT SISA
    BAGI SISA 256
    PANGGIL_PARAM TULIS_BYTE FD_OUT SISA
BATAS_FUNGSI

GLOBAL OP_PROGRAM_UTAMA 255
GLOBAL OP_BATAS_PROGRAM 60
GLOBAL OP_CETAK_TEKS 21
GLOBAL OP_CETAK_ANGKA 22
GLOBAL OP_SIMPAN 10
GLOBAL OP_TAMBAH 11
GLOBAL OP_KURANG 12
GLOBAL OP_BILA_SAMA 30
GLOBAL OP_BATAS_BILA 31

FUNGSI_PARAM TULIS_ELF_HEADER FD
    PANGGIL_PARAM TULIS_BYTE FD 127
    PANGGIL_PARAM TULIS_BYTE FD 69
    PANGGIL_PARAM TULIS_BYTE FD 76
    PANGGIL_PARAM TULIS_BYTE FD 70
    PANGGIL_PARAM TULIS_BYTE FD 2
    PANGGIL_PARAM TULIS_BYTE FD 1
    PANGGIL_PARAM TULIS_BYTE FD 1
    PANGGIL_PARAM TULIS_BYTE FD 0
    ULANGI 7
        PANGGIL_PARAM TULIS_BYTE FD 0
    BATAS_ULANGI
BATAS_FUNGSI

FUNGSI_PARAM TULIS_BUFFER_KODE FD_OUT
    SIMPAN I 0
    SIMPAN HURUF 0
    SIMPAN HURUF_DEPAN 0
    SELAMA_KURANG I PANJANG_TOKEN
        ARRAY_AMBIL HURUF BUFFER_TOKEN I
        BILA_SAMA HURUF 34
            NAIK I
            LANJUTKAN
        BATAS_BILA
        BILA_SAMA HURUF 92
            NAIK I
            ARRAY_AMBIL HURUF_DEPAN BUFFER_TOKEN I
            BILA_SAMA HURUF_DEPAN 110
                PANGGIL_PARAM TULIS_BYTE FD_OUT 10
            LAINNYA
                PANGGIL_PARAM TULIS_BYTE FD_OUT 92
                PANGGIL_PARAM TULIS_BYTE FD_OUT HURUF_DEPAN
            BATAS_BILA
            NAIK I
            LANJUTKAN
        BATAS_BILA
        PANGGIL_PARAM TULIS_BYTE FD_OUT HURUF
        NAIK I
    BATAS_SELAMA
    PANGGIL_PARAM TULIS_BYTE FD_OUT 0
BATAS_FUNGSI

FUNGSI_KEMBALI HITUNG_SIDIK_JARI
    SIMPAN TOTAL 0
    SIMPAN I 0
    SIMPAN PENGALI 1
    SIMPAN HURUF 0
    SIMPAN SEMENTARA 0
    SELAMA_KURANG I PANJANG_TOKEN
        ARRAY_AMBIL HURUF BUFFER_TOKEN I
        UBAH SEMENTARA HURUF
        KALI SEMENTARA PENGALI
        TAMBAH TOTAL SEMENTARA
        NAIK I
        NAIK PENGALI
    BATAS_SELAMA
    KEMBALIKAN TOTAL
BATAS_FUNGSI

PROGRAM_UTAMA
    CETAK_TEKS "=== KOMPILATOR BINER V4 (BEBAS HANG) ===\n"
    BUKA_BACA "input.ouro" FILE_IN
    BUKA_FILE "output.obf" FILE_OUT

    PANGGIL_PARAM TULIS_ELF_HEADER FILE_OUT
    PANGGIL_PARAM TULIS_BYTE FILE_OUT 64
    PANGGIL_PARAM TULIS_BYTE FILE_OUT 0

    SIMPAN ADA_KATA 1
    SIMPAN SIDIK_JARI 0

    SELAMA_SAMA ADA_KATA 1
        PANGGIL_KEMBALI ADA_KATA BACA_TOKEN FILE_IN

        BILA_SAMA ADA_KATA 1
            PANGGIL_KEMBALI SIDIK_JARI HITUNG_SIDIK_JARI

            BILA_SAMA SIDIK_JARI 6953
                PANGGIL_PARAM TULIS_BYTE FILE_OUT OP_PROGRAM_UTAMA
                LANJUTKAN
            BATAS_BILA

            BILA_SAMA SIDIK_JARI 7013
                PANGGIL_PARAM TULIS_BYTE FILE_OUT OP_BATAS_PROGRAM
                LANJUTKAN
            BATAS_BILA

            BILA_SAMA SIDIK_JARI 4307
                PANGGIL_PARAM TULIS_BYTE FILE_OUT OP_CETAK_TEKS
                PANGGIL_KEMBALI ADA_KATA BACA_TOKEN FILE_IN
                PANGGIL_PARAM TULIS_BUFFER_KODE FILE_OUT
                LANJUTKAN
            BATAS_BILA

            BILA_SAMA SIDIK_JARI 4845
                PANGGIL_PARAM TULIS_BYTE FILE_OUT 22
                PANGGIL_KEMBALI ADA_KATA BACA_TOKEN FILE_IN
                PANGGIL_PARAM TULIS_BUFFER_KODE FILE_OUT
                LANJUTKAN
            BATAS_BILA

            BILA_SAMA SIDIK_JARI 1573
                PANGGIL_PARAM TULIS_BYTE FILE_OUT 10
                PANGGIL_KEMBALI ADA_KATA BACA_TOKEN FILE_IN
                PANGGIL_PARAM TULIS_BUFFER_KODE FILE_OUT
                PANGGIL_KEMBALI ADA_KATA BACA_TOKEN FILE_IN
                PANGGIL_KEMBALI NILAI_ASLI STRING_KE_ANGKA
                PANGGIL_PARAM TULIS_ANGKA_4BYTE FILE_OUT NILAI_ASLI
                LANJUTKAN
            BATAS_BILA

            BILA_SAMA SIDIK_JARI 1466
                PANGGIL_PARAM TULIS_BYTE FILE_OUT OP_TAMBAH
                PANGGIL_KEMBALI ADA_KATA BACA_TOKEN FILE_IN
                PANGGIL_PARAM TULIS_BUFFER_KODE FILE_OUT
                PANGGIL_KEMBALI ADA_KATA BACA_TOKEN FILE_IN
                PANGGIL_KEMBALI NILAI_ASLI STRING_KE_ANGKA
                PANGGIL_PARAM TULIS_ANGKA_4BYTE FILE_OUT NILAI_ASLI
                LANJUTKAN
            BATAS_BILA

            BILA_SAMA SIDIK_JARI 1567
                PANGGIL_PARAM TULIS_BYTE FILE_OUT OP_KURANG
                PANGGIL_KEMBALI ADA_KATA BACA_TOKEN FILE_IN
                PANGGIL_PARAM TULIS_BUFFER_KODE FILE_OUT
                PANGGIL_KEMBALI ADA_KATA BACA_TOKEN FILE_IN
                PANGGIL_KEMBALI NILAI_ASLI STRING_KE_ANGKA
                PANGGIL_PARAM TULIS_ANGKA_4BYTE FILE_OUT NILAI_ASLI
                LANJUTKAN
            BATAS_BILA
            
        BATAS_BILA
    BATAS_SELAMA

    TUTUP_FILE FILE_IN
    TUTUP_FILE FILE_OUT
    CETAK_TEKS "-> Kompilasi Biner Selesai!\n"
BATAS_PROGRAM
"""

found = False
for root, dirs, files in os.walk('.'):
    if 'kompilator.ouro' in files:
        filepath = os.path.join(root, 'kompilator.ouro')
        with open(filepath, 'w') as f:
            f.write(kode_baru.strip() + '\n')
        print(f"[OK] Berhasil memperbarui {filepath} ke V4")
        found = True

if not found:
    print("File kompilator.ouro tidak ditemukan!")
